{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.database | quote }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.volumeMount.name }}
              mountPath: {{ .Values.volumeMount.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volumeClaimTemplate.name }}
      spec:
        accessModes:
{{ toYaml .Values.volumeClaimTemplate.accessModes | nindent 10 }}
        storageClassName: {{ .Values.volumeClaimTemplate.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.volumeClaimTemplate.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appLabel }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
  type: {{ .Values.serviceType }}
{{- end }}
