{{- if .Values.authService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authService.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.authService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.authService.name }}
{{- with .Values.authService.strategy }}
  strategy:
{{ toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.authService.name }}
    spec:
{{- with .Values.authService.podSecurityContext }}
      securityContext:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Values.authService.name }}
          image: {{ .Values.authService.image }}
          imagePullPolicy: {{ .Values.authService.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.authService.containerPort }}
{{- with .Values.authService.env }}
          env:
{{ toYaml . | nindent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.authService.resources | nindent 12 }}
{{- with .Values.authService.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.authService.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.authService.name }}
  ports:
    - port: {{ .Values.authService.servicePort }}
      targetPort: {{ .Values.authService.serviceTargetPort }}
  type: {{ .Values.authService.serviceType }}
{{- end }}
