{{- if .Values.gateway.enabled }}
apiVersion: {{ .Values.gateway.apiVersion }}
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
{{ toYaml .Values.gateway.listeners | nindent 4 }}
{{- end }}
