{{- if .Values.mongo.statefulSet.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongo.statefulSet.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mongo.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongo.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.appLabel }}
    spec:
      containers:
        - name: {{ .Values.mongo.statefulSet.name }}
          image: {{ .Values.mongo.statefulSet.image }}
{{- with .Values.mongo.statefulSet.imagePullPolicy }}
          imagePullPolicy: {{ . }}
{{- end }}
          ports:
            - containerPort: {{ .Values.mongo.statefulSet.containerPort }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.statefulSet.database | quote }}
{{- with .Values.mongo.statefulSet.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
            - name: {{ .Values.mongo.statefulSet.volumeMount.name }}
              mountPath: {{ .Values.mongo.statefulSet.volumeMount.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.mongo.statefulSet.volumeClaimTemplate.name }}
      spec:
        accessModes:
{{ toYaml .Values.mongo.statefulSet.volumeClaimTemplate.accessModes | nindent 10 }}
        storageClassName: {{ .Values.mongo.statefulSet.volumeClaimTemplate.storageClassName | quote }}
        resources:
          requests:
            storage: {{ .Values.mongo.statefulSet.volumeClaimTemplate.size }}
{{- end }}
{{- if and .Values.mongo.statefulSet.enabled .Values.mongo.service.enabled }}
---
{{- end }}
{{- if .Values.mongo.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mongo.appLabel }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  type: {{ .Values.mongo.service.type }}
{{- end }}
