enabled: true
namespace: dev
name: auth-service
replicas: 1
image: thanusri22/auth-service:v1.1.1
imagePullPolicy: Always
containerPort: 3001
servicePort: 3001
serviceTargetPort: 3001
serviceType: ClusterIP
env:
  - name: PORT
    value: "3001"
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: MONGODB_URI
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: JWT_SECRET
  - name: JWT_EXPIRES_IN
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: JWT_EXPIRES_IN
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
