enabled: true
namespace: dev
appLabel: mongo
name: mongo
replicas: 1
image: mongo
imagePullPolicy: IfNotPresent
containerPort: 27017
database: taskflow

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"

volumeMount:
  name: mongo-vct
  mountPath: /data/db

volumeClaimTemplate:
  name: mongo-vct
  accessModes:
    - ReadWriteMany
  storageClassName: storage
  size: 2Gi

servicePort: 27017
serviceTargetPort: 27017
serviceType: ClusterIP
