enabled: true
namespace: dev
name: user-service
replicas: 1
image: thanusri22/user-service:v1.1.1
imagePullPolicy: Always
containerPort: 3002
servicePort: 3002
serviceTargetPort: 3002
serviceType: ClusterIP
env:
  - name: PORT
    value: "3002"
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: MONGODB_URI
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
