apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-mongo-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: taskflow
  source:
    repoURL: https://github.com/Thanu-sri1/task-ust.git
    targetRevision: main
    path: helm/mongo
    helm:
      releaseName: taskflow-mongo-prod
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
