enabled: true
namespace: dev
name: analytics-service
replicas: 1
image: thanusri22/analytics-service:v1.1.1
imagePullPolicy: Always
containerPort: 3005
servicePort: 3005
serviceTargetPort: 3005
serviceType: ClusterIP
env:
  - name: PORT
    value: "3005"
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: MONGODB_URI
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
