enabled: true
namespace: dev
name: task-service
replicas: 1
image: thanusri22/task-service:v1.1.1
imagePullPolicy: Always
containerPort: 3003
servicePort: 3003
serviceTargetPort: 3003
serviceType: ClusterIP
env:
  - name: PORT
    value: "3003"
  - name: MONGODB_URI
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: MONGODB_URI
  - name: NOTIFICATION_SERVICE_URL
    valueFrom:
      configMapKeyRef:
        name: app-config
        key: NOTIFICATION_SERVICE_URL
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
