apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: taskflow
  source:
    repoURL: https://github.com/Thanu-sri1/task-ust.git
    targetRevision: main
    path: helm
    helm:
      releaseName: taskflow-prod
      valueFiles:
        - values-prod.yaml
      values: |
        mongoPersistentVolume:
          enabled: false
        mongoPersistentVolumeClaim:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
