apiVersion: v2
name: taskflow
description: Umbrella chart for TaskFlow microservices
type: application
version: 0.1.0
appVersion: "1.1.1"
dependencies:
  - name: taskflow-shared
    version: 0.1.0
    repository: file://./shared
    alias: shared
  - name: taskflow-mongo
    version: 0.1.0
    repository: file://./mongo
    alias: mongo
  - name: taskflow-auth-service
    version: 0.1.0
    repository: file://./auth-service
    alias: auth-service
  - name: taskflow-user-service
    version: 0.1.0
    repository: file://./user-service
    alias: user-service
  - name: taskflow-task-service
    version: 0.1.0
    repository: file://./task-service
    alias: task-service
  - name: taskflow-notification-service
    version: 0.1.0
    repository: file://./notification-service
    alias: notification-service
  - name: taskflow-analytics-service
    version: 0.1.0
    repository: file://./analytics-service
    alias: analytics-service
  - name: taskflow-api-gateway
    version: 0.1.0
    repository: file://./api-gateway
    alias: api-gateway
  - name: taskflow-frontend
    version: 0.1.0
    repository: file://./frontend
    alias: frontend
